; Default vale config for files that don't have a dedicated .vale.ini
Packages = write-good
MinAlertLevel = suggestion
Vocab = nvimDict

[*.{md,txt,rst}]
BasedOnStyles = Vale, write-good
; Disable noisy write-good rules (too much signal when writing prose)
write-good.E-Prime = NO
write-good.Weasel = NO
write-good.TooWordy = NO
write-good.So = NO
write-good.ThereIs = NO
