[font]
size = 11.0

[font.normal]
family = "Mononoki Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Mononoki Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Mononoki Nerd Font Mono"
style = "Italic"

[env]
TERM = "xterm-256color"
